# **NumPy Installation**

Google Colab and Anaconda Package include Python, NumPy, and other commonly used packages for scientific computing and data science.

NumPy can be installed with conda, with pip, or with a package manager on different OS.

If you use conda, you can install it with:
**conda install numpy**

If you use pip, you can install it with:
**pip install numpy**

But here we don't need any installation process.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## Creating arrays from Existing Data

In [3]:
import numpy as np
numbers = np.array([2, 3, 5, 7, 11])
numbers

array([ 2,  3,  5,  7, 11])

In [4]:
type(numbers)

numpy.ndarray

**Multidimensional Arguments**

1D array

In [5]:
array_1D = np.array([2,4,5,6])
array_1D

array([2, 4, 5, 6])

2D array

In [6]:
array_2D = np.array([[2,4,5,6],[2,4,5,6],[2,4,5,6]]) ## 3X4 array--(3 rows and 4 columns)
array_2D 

array([[2, 4, 5, 6],
       [2, 4, 5, 6],
       [2, 4, 5, 6]])

3D array

In [7]:
array_3D = np.array([[[2,4,5,6],[2,4,5,6],[2,4,5,6]]])
array_3D 

array([[[2, 4, 5, 6],
        [2, 4, 5, 6],
        [2, 4, 5, 6]]])

## **Array Attributes**

In [8]:
integers = np.array([[1, 2, 3], [4, 5, 6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [10]:
strings = np.array(['apple','big','cat'])
strings 

array(['apple', 'big', 'cat'], dtype='<U5')

Checking an array's element types

In [11]:
integers.dtype

dtype('int64')

In [12]:
floats.dtype

dtype('float64')

In [13]:
strings.dtype

dtype('<U5')

Checking an array’s Dimensions and Shape

In [14]:
array_1D.ndim

1

In [15]:
array_2D.ndim

2

In [16]:
array_3D.ndim

3

In [17]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
integers.ndim

2

In [19]:
integers.shape

(2, 3)

In [20]:
integers.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
array_3D.shape

(1, 3, 4)

In [22]:
array_2D.shape

(3, 4)

Checking an array’s Number of Elements and Element Size

In [23]:
integers.size

6

In [24]:
integers.itemsize

8

In [25]:
floats.size

5

In [26]:
floats.itemsize

8

#**Array Operators**

In [27]:
x = np.arange(4)

In [28]:
x+10 #scalar addition is element wise

array([10, 11, 12, 13])

In [29]:
x*2 #scalar multiplication is element wise

array([0, 2, 4, 6])

In [30]:
x+x #array addition is element wise

array([0, 2, 4, 6])

In [31]:
x*x #array multiplicatio is element wise

array([0, 1, 4, 9])

In [32]:
x/10 #array division is element wise

array([0. , 0.1, 0.2, 0.3])

In [33]:
x//10

array([0, 0, 0, 0])

In [34]:
x**3

array([ 0,  1,  8, 27])

In [35]:
x = np.array([[11,9,11],[2,15,18]])

In [36]:
x>10

array([[ True, False,  True],
       [False,  True,  True]])

In [37]:
x>=10

array([[ True, False,  True],
       [False,  True,  True]])

In [38]:
x<10

array([[False,  True, False],
       [ True, False, False]])

In [39]:
x<=10

array([[False,  True, False],
       [ True, False, False]])

In [40]:
x==9

array([[False,  True, False],
       [False, False, False]])

In [41]:
x!=11

array([[False,  True, False],
       [ True,  True,  True]])

#**NumPy Methods**

In [42]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [43]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [44]:
grades.max()

100

In [45]:
grades.min()

70

In [46]:
grades.sum()

1054

In [47]:
grades.std()

8.792357792739987

In [48]:
grades.mean()

87.83333333333333

In [49]:
grades.var()

77.30555555555556

In [50]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [51]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

#**Indexing and Selection**

In [52]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
arr_2d[1]

array([20, 25, 30])

In [54]:
arr_2d[1][0]

20

In [55]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])